### ISSUE TITLE
不支持aslain replays分目录的功能

### ISSUE THREAD

**Issue by hawkli** [bbaoqaq/wowsCheaterViewer#1]
如果使用了aslain的replays按版本目录功能，本程序无法正常读到json文件，而导致不能正常工作，建议做兼容。

另外说几个使用的小问题点：
变量名能不能正规点？address_yuyukoWowsApi_域名1  这样的命名，有点受不了。
https://dev-proxy.wows.shinoaki.com:7700，这个地址，似乎有时在更新不稳定？我反正报了一天的http 405错误，今天早上试了一下又好的，这个不稳定直接导致客户端无法启动crash掉，建议多try一下错误，提高稳定性。

**Comment by bbaoqaq** [comment]
你好，谢谢你提的issue，这是我第一次用github也是第一次收到issue，非常谢谢你的留言。

1、关于replay整理mod已经有朋友给我提了，之后会看情况换成选rep目录而非选择游戏根目录来解决。
2、关于变量命名，之前我是学习低代码开发的，支持中文变量名。所以对难以描述业务逻辑的变量，我习惯采用中文命名混合。谢谢你的建议我之后会考虑更改（如果没有什么好想法我就不改了dbq）。
3、有关yuyuko api的三个地址，前两个域名指向的是同一个服务器。近期yuyuko机器人会做更新，将所有的api转移到新服务器，也就是第三个域名上，未来会弃用老服务器和老域名（我也在注释中写了）。而转移工作正在进行，所以新域名上有部分功能不可使用要到老域名上才能调用，也有不稳定的情况。你可以在[这里](https://v3-api.wows.shinoaki.com/v3/webjars/swagger-ui/index.html#/)查看到新域名已经可用的功能。
我已经在程序中针对信息获取失败的情况进行优化（访问域名3如果失败了，就用域名2进行重试），你可以重新拉取一下。

再次感谢你的建议。

**Comment by hawkli** [comment]
不稳定的原因我似乎也有定位了，应该是某次没刷出战绩来，我多按了几次刷新，可能导致了访问次数超过某个API的限频，然后把我的IP封了，我观察了几天，都没有改变，但我用其他公网IP的电脑访问是正常的。
如果根据我所设想的，那可能手动点刷新这个功能会存在风险的，需要考虑怎么处理。

**Comment by hawkli** [comment]
既然你准备解决replays的问题，那这个issue我就关了。
不过你这次更新的版本，又加了自动更新功能，然而会下载郭楠查看器……唉，一言难尽

**Comment by bbaoqaq** [comment]
对不起呜呜呜，之前一直都没正式发布，后面想着发布出去之后这个名字不太好，就换了项目名称。然后更新脚本的项目名称又没法换就寄了。想着反正现在是小范围使用，等正式发布了之后应该就更新不到老版本了，就摆烂不管了（
（花了一下午改了一下，把大部分规范性提示都改好了，你可以再拉取一下，希望你看的时候血压低一点，萌新的第一个项目dbq）

顺便能不能问一下你是哪个群友，还是自己搜到的（

**Comment by hawkli** [comment]
我看到网上截图，然后翻到你的源码，没找到release版本，就自己编译了用的。
我昨晚又拿新的版本编译了一个，IP没变忽然又能用了，暂时不清楚http 405那个错是不是网站把我的IP放出来了还是程序还有啥BUG导致的，反正现在好用了。
